name: Unity

on:
#  push:
#    branches:
#      - main
  release:
    types: [published]
  # todo: remove this after fix
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: WebGL Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: ${{ runner.os }}-unity-library-${{ hashFiles('Assets/**', 'ProjectSettings/**') }}
          restore-keys: |
            ${{ runner.os }}-unity-library-
      - name: Build as WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: auto # honor ProjectSettings/ProjectVersion.txt
          targetPlatform: WebGL
      - name: Upload build result as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          name: webgl-build
          path: build
  deploy:
    name: Deployment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4