name: GitHub Pages

on:
  push:
    branches:
      - main
  # alternatively: to build on every release
  # release:
  #   types: [published]

  # todo: remove this after fix
  pull_request:
    branches:
      - '*'

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  build:
    name: WebGL Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ github.event.repository.name }}-WebGL
          restore-keys: |
            Library-${{ github.event.repository.name }}"-
            Library-
      - name: Free Ubuntu Runner's Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed if set to "true" but frees about 6 GB
          tool-cache: false
          # all of these default to true, but feel free to set to "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Build Unity Project to /build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          # auto will honor Unity version specified at ProjectSettings/ProjectVersion.txt
          unityVersion: auto
          targetPlatform: WebGL
      - name: Upload "build/WebGL/WebGL/" as artifact pages
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          # name needs to be letter lock or it won't work
          name: github-pages
          path: build/WebGL/WebGL/
  deploy:
    name: Deployment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy the whole /build as Pages
        id: deployment
        uses: actions/deploy-pages@v4
